# Site settings
title: Onesimus Systems
email: lee@onesimussystems.com
description: "Official blog and news source for Onesimus Systems."
baseurl: ""
url: "http://blog.onesimussystems.com"
github_username:  onesimus-systems

# Build settings
markdown: kramdown
