# Site settings
title: Onesimus Systems
email: onesimussystems@gmail.com
description: "Official blog and news source for Onesimus Systems."
baseurl: ""
url: "http://onesimussystems.com"
github_username:  onesimus-systems

# Build settings
markdown: kramdown
